language: cpp
dist: xenial
jobs:
  include:
    - stage:
      name: "Autotools"
      script:
        - ./bootstrap.sh
        - ./configure
        - make
        - cd tests && make check
    -
      addons:
         snaps:
          - name: cmake
            confinement: classic
      name: "CMake"
      script:
        - snap run cmake -H. -B_build -DCMAKE_VERBOSE_MAKEFILE=ON -DWITH_TESTS=ON
        - snap run cmake --build _build
        - snap run cmake --build _build --target test
        - snap run cmake --build _build --target package