language: cpp
dist: xenial
script:
  - cmake -H. -B_build -DCMAKE_VERBOSE_MAKEFILE=ON
  - cmake --build _build
  - cmake --build _build --target test
  - ./bootstrap.sh
  - ./configure
  - make
  - cd tests && make check
