language: cpp
dist: xenial
addons:
   apt:
      sources:
      - ubuntu-toolchain-r-test
      packages:
      - g++-9
jobs:
   include:
   -  stage: null
      name: Autotools
      script:
      - ./bootstrap.sh
      - ./configure
      - make
      - cd tests && make check
   -  addons:
         snaps:
         -  name: cmake
            confinement: classic
      name: CMake
      script:
      - snap run cmake -H. -B_build -DCMAKE_VERBOSE_MAKEFILE=ON -DWITH_TESTS=ON -DCXX_COMPILER="g++-9"
      - snap run cmake --build _build
      - snap run cmake --build _build --target test
      - snap run cmake --build _build --target package