language: cpp
dist: xenial
addons:
     snaps:
       - name: cmake
         confinement: classic
jobs:
  include:
    - stage:
      name: "Autotools"
      script:
        - ./bootstrap.sh
        - ./configure
        - make
        - cd tests && make check
    -
      name: "CMake"
      script:
        - snap run cmake -H. -B_build -DCMAKE_VERBOSE_MAKEFILE=ON
        - snap run cmake --build _build
        - snap run cmake --build _build --target test
        - snap run cmake --build _build --target package