language: cpp
dist: xenial
script:
  - cmake -H. -B_build
  - cmake --build _build
  - cmake --build _build --target test
  - echo Automake
  - ./bootstrap.sh
  - ./configure
  - make
  - cd tests && make check
